Feature/9 apply docker
KT-AICare/aicare-monitoring pull request #13
Opened 2024-03-29 06:41 UTC by inchangson

- server app docker image로 build
  - server app 정상 실행 확인 차 spring-boot-starter-web dependency 추가
  - github actions 에선 `Started [a-zA-Z0-9]* in [0-9.]* seconds` 패턴 매칭으로 확인
- 해당 image docker hub로 push
- docker-compose에 server-app 서비스 추가

2024-03-29 08:56 UTC, yhwcs requested changes
리뷰 확인 부탁드립니다~

2024-03-29 08:56 UTC, yhwcs commented on .github/workflows/java-build-actions.yml
> +  docker-image:
update docker image에 적절한 trigger를 고민해봅시다

2024-03-29 08:56 UTC, yhwcs commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
web...

2024-04-01 02:12 UTC, inchangson commented
@yhwcs pr 부탁드립니다
- spring-boot-web 삭제
- workflow PR 시 동작 조건 변경(default:opened, reopened, synchronized -> closed)
- docker image push, dependency graph 제출은 PR Merged 때만 동작하도록 변경

2024-04-01 02:23 UTC, yhwcs approved these changes
확인했습니다.

2024-04-01 02:31 UTC, merged